modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}" # MIT

issueTrackerURL="https://github.com/yayEvy/vscreate/issues"

[[mods]] #mandatory
modId="vscreate"
version="${mod_version}"
displayName="${mod_name}"

displayURL="https://github.com/yayEvy/vscreate"

logoFile="image.png"

#credits="" #optional

authors="${mod_authors}"

description='''${mod_description}'''

# dependencies
[[dependencies.vscreate]]
    modId="forge"
    mandatory=true #mandatory is mandatory
    versionRange="${forge_version_range}"

    ordering="NONE"
    side="BOTH"

[[dependencies.vscreate]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"

    ordering="NONE"
    side="BOTH"

# version ranges might need to be changed later
[[dependencies.vscreate]]
    modId="valkyrienskies"
    mandatory=true
    versionRange="[2.5.0-beta.3+237c68468b]"

    ordering="NONE"
    side="BOTH"

[[dependencies.vscreate]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.j-55]"

    ordering="NONE"
    side="BOTH"